### ISSUE TITLE
Y axis canvas doesn't resize with Y axis container

### ISSUE THREAD

**Issue by amgottsegen** [CMU-CREATE-Lab/experimental-fast-timeline#8]

**Comment by chrisbartley** [comment]
Can you share code demonstrating the problem?  If I'm understanding correctly, it at least works when this library is used with Plot Manager wrapper.  See http://bodytrack.github.io/plot-manager/examples/createlab-grapher/index2.html

Here's the code from PlotManager which handles mutating the height of a PlotContainer: https://github.com/BodyTrack/plot-manager/blob/master/js/org/bodytrack/grapher/PlotManager.js#L939-L954 

And here's the method which handles mutating the height of a YAxis: https://github.com/BodyTrack/plot-manager/blob/master/js/org/bodytrack/grapher/PlotManager.js#L481-L490

**Comment by pdille** [comment]
Ah, that last method seems key. The background to this report is that the grapher doesn't seem to auto resize the y-axis canvas as its container div changes on screen resize. It does correctly resize the other canvas elements - plot container, etc, etc - though.

Cool, so I think we can then just call this setHeight in the window resize handler.

**Comment by amgottsegen** [comment]
Yes that worked spectacularly, thanks!
